#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import re

def fix_all_template_links():
    templates_dir = 'templates'
    
    # Route mapping - Türkçe metinleri İngilizce route'lara çevir
    route_mapping = {
        'Dashboard': 'dashboard',
        'Ana Sayfa': 'dashboard', 
        'Ana Sayfa': 'dashboard',
        'Ürünler': 'urunler',
        'Stok Yönetimi': 'urunler',
        'Cariler': 'cariler',
        'Cari Hesaplar': 'cariler',
        'Raporlar': 'raporlar',
        'Teklifler': 'dashboard',  # temporary
        'Satışlar': 'pos',
        'POS': 'pos',
        'Siparişler': 'dashboard',  # temporary
        'Tedarikçiler': 'cariler',
        'Ayarlar': 'ayarlar',
        'İadeler': 'dashboard',  # temporary
        'Faturalar': 'dashboard',  # temporary
        'Kasa': 'pos',
        'Envanter': 'urunler',
        'Müşteriler': 'cariler',
        'Tedarikçi': 'cariler',
        'Hızlı Rapor': 'raporlar',
        'Yardım': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Settings': 'ayarlar',
        'Logout': 'cikis',
        'Çıkış': 'cikis',
        'Geri': 'dashboard',
        'İleri': 'dashboard',
        'Kaydet': 'dashboard',
        'İptal': 'dashboard',
        'Yeni': 'urun_ekle',
        'Düzenle': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
        'Reddet': 'dashboard',
        'İptal Et': 'dashboard',
        'Oluştur': 'dashboard',
        'Seç': 'dashboard',
        'Temizle': 'dashboard',
        'Yenile': 'dashboard',
        'Kopyala': 'dashboard',
        'Taşı': 'dashboard',
        'İçe Aktar': 'dashboard',
        'Dışa Aktar': 'dashboard',
        'Yeniden Fiyatlandır': 'toplu_fiyat_guncelleme',
        'Toplu İşlem': 'dashboard',
        'Tümünü Seç': 'dashboard',
        'Tümünü İptal': 'dashboard',
        'Yeniden Adlandır': 'dashboard',
        'Sırala': 'dashboard',
        'Filtrele': 'dashboard',
        'Önizle': 'dashboard',
        'Sonraki Sayfa': 'dashboard',
        'Önceki Sayfa': 'dashboard',
        'İlk Sayfa': 'dashboard',
        'Son Sayfa': 'dashboard',
        'Geçersiz': 'dashboard',
        'Geçerli': 'dashboard',
        'Başarılı': 'dashboard',
        'Hata': 'dashboard',
        'Uyarı': 'dashboard',
        'Bilgi': 'dashboard',
        'Kapat': 'dashboard',
        'Tamamla': 'dashboard',
        'İptal': 'dashboard',
        'Kaydet': 'dashboard',
        'Güncelle': 'dashboard',
        'Yenile': 'dashboard',
        'Sil': 'dashboard',
        'Detay': 'dashboard',
        'Yazdır': 'dashboard',
        'Filtrele': 'dashboard',
        'Excel': 'dashboard',
        'PDF': 'dashboard',
        'Arama': 'dashboard',
        'Ekle': 'urun_ekle',
        'Güncelle': 'dashboard',
        'Listele': 'dashboard',
        'Göster': 'dashboard',
        'Yönet': 'dashboard',
        'Kontrol Et': 'dashboard',
        'Onayla': 'dashboard',
    }
    
    print(f"{len(route_mapping)} dosyasını düzelt")
    for filename in os.listdir(templates_dir):
        if filename.endswith('.html'):
            filepath = os.path.join(templates_dir, filename)
            
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Replace href="#" with url_for
            original_content = content
            modified_content = content
            
            # Replace href="#" patterns with url_for
            for display_name, route_name in route_mapping.items():
                # Pattern: href="#">Display</a>
                pattern1 = rf'href="#">{re.escape(display_name)}</a>'
                replacement1 = 'href="{{ url_for(\'{}\') }}">{}</a>'.format(route_name, display_name)
                modified_content = re.sub(pattern1, replacement1, modified_content)
                
                # Pattern: href="#">Display</span>
                pattern2 = rf'href="#">{re.escape(display_name)}</span>'
                replacement2 = 'href="{{ url_for(\'{}\') }}">{}</span>'.format(route_name, display_name)
                modified_content = re.sub(pattern2, replacement2, modified_content)
                
                # Replace onclick patterns
                modified_content = re.sub(r'onclick="window\.location\.href=[\'"]#*[\'"]"', '', modified_content)
            
            if modified_content != original_content:
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(modified_content)
                print(f"Fixed links in {filename}")

if __name__ == '__main__':
    fix_all_template_links()
    print("Tüm linkler düzeltildi!")
