"""initial schema

Revision ID: 2d1b00ba9040
Revises: 
Create Date: 2026-06-02 10:47:41.910412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1b00ba9040'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('user_limit', sa.Integer(), nullable=True),
    sa.Column('product_limit', sa.Integer(), nullable=True),
    sa.Column('module_permissions', sa.Text(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('subscription_start', sa.Date(), nullable=True),
    sa.Column('subscription_end', sa.Date(), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('subscription_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('subscription_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('firma_adi', sa.String(length=100), nullable=False),
    sa.Column('yetkili_adi', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('vergi_dairesi', sa.String(length=100), nullable=True),
    sa.Column('vergi_numarasi', sa.String(length=100), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('kayit_tarihi', sa.DateTime(), nullable=True),
    sa.Column('paket_tipi', sa.String(length=20), nullable=True),
    sa.Column('urun_limiti', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=True),
    sa.Column('platform_role', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('iban', sa.String(length=40), nullable=True),
    sa.Column('bank_name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_account_name')
    )
    op.create_table('action_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backup_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('backup_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unvan', sa.String(length=200), nullable=False),
    sa.Column('yetkili', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('vergidairesi', sa.String(length=100), nullable=True),
    sa.Column('vergi_numarasi', sa.String(length=100), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('tipi', sa.String(length=20), nullable=True),
    sa.Column('borc', sa.Float(), nullable=True),
    sa.Column('alacak', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kayit_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_category_name')
    )
    op.create_table('departman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ad', name='uq_user_departman_ad')
    )
    op.create_table('support_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('urun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barkod', sa.String(length=50), nullable=True),
    sa.Column('urun_adi', sa.String(length=200), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('alis_fiyati', sa.Float(), nullable=True),
    sa.Column('satis_fiyati', sa.Float(), nullable=True),
    sa.Column('stok_miktari', sa.Float(), nullable=True),
    sa.Column('kritik_stok', sa.Float(), nullable=True),
    sa.Column('depo_adi', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('eklenme_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_warehouse_name')
    )
    op.create_table('account_reconciliation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('recon_date', sa.Date(), nullable=False),
    sa.Column('expected_balance', sa.Float(), nullable=True),
    sa.Column('counted_balance', sa.Float(), nullable=True),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_item_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_item_id'], ['action_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cari_hareket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cari_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('islem_tipi', sa.String(length=20), nullable=False),
    sa.Column('tutar', sa.Float(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('odeme_turu', sa.String(length=50), nullable=True),
    sa.Column('referans_id', sa.Integer(), nullable=True),
    sa.Column('referans_tip', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cari_id'], ['cari.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('cari_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('islem_tipi', sa.String(length=20), nullable=False),
    sa.Column('tutar', sa.Float(), nullable=False),
    sa.Column('odeme_turu', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('referans_id', sa.Integer(), nullable=True),
    sa.Column('referans_tip', sa.String(length=20), nullable=True),
    sa.Column('ip_adresi', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['cari_id'], ['cari.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cari_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('iade_turu', sa.String(length=50), nullable=False),
    sa.Column('iade_sebebi', sa.Text(), nullable=False),
    sa.Column('iade_tutari', sa.Float(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('urun_adet', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('ip_adresi', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cari_id'], ['cari.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sicil_no', sa.String(length=50), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('tc_kimlik', sa.String(length=11), nullable=True),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('cinsiyet', sa.String(length=10), nullable=True),
    sa.Column('medeni_hal', sa.String(length=20), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('ehliyet', sa.String(length=20), nullable=True),
    sa.Column('ehliyet_no', sa.String(length=50), nullable=True),
    sa.Column('kan_grubu', sa.String(length=10), nullable=True),
    sa.Column('acil_durum_kisi', sa.String(length=100), nullable=True),
    sa.Column('acil_durum_telefon', sa.String(length=20), nullable=True),
    sa.Column('profil_foto', sa.String(length=255), nullable=True),
    sa.Column('ise_giris_tarihi', sa.Date(), nullable=False),
    sa.Column('ise_cikis_tarihi', sa.Date(), nullable=True),
    sa.Column('calisma_durumu', sa.String(length=20), nullable=True),
    sa.Column('departman_id', sa.Integer(), nullable=True),
    sa.Column('pozisyon', sa.String(length=100), nullable=True),
    sa.Column('maas', sa.Float(), nullable=True),
    sa.Column('sgk_no', sa.String(length=50), nullable=True),
    sa.Column('vergi_no', sa.String(length=50), nullable=True),
    sa.Column('iban', sa.String(length=50), nullable=True),
    sa.Column('banka_adi', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departman_id'], ['departman.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sicil_no', name='uq_user_personel_sicil')
    )
    op.create_table('satis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=False),
    sa.Column('cari_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('depo', sa.String(length=100), nullable=True),
    sa.Column('ara_toplam', sa.Float(), nullable=True),
    sa.Column('kdv_orani', sa.Float(), nullable=True),
    sa.Column('kdv_tutar', sa.Float(), nullable=True),
    sa.Column('iskonto', sa.Float(), nullable=True),
    sa.Column('genel_toplam', sa.Float(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cari_id'], ['cari.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fatura_no')
    )
    op.create_table('stok_hareket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('islem_tipi', sa.String(length=20), nullable=False),
    sa.Column('miktar', sa.Float(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('depo', sa.String(length=100), nullable=True),
    sa.Column('eski_stok', sa.Float(), nullable=True),
    sa.Column('yeni_stok', sa.Float(), nullable=True),
    sa.Column('cari_id', sa.Integer(), nullable=True),
    sa.Column('ip_adresi', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cari_id'], ['cari.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_ticket_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_staff_reply', sa.Boolean(), nullable=True),
    sa.Column('attachment_filename', sa.String(length=255), nullable=True),
    sa.Column('attachment_original_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_content_type', sa.String(length=120), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teklif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teklif_no', sa.String(length=50), nullable=False),
    sa.Column('cari_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('gecerlilik_tarihi', sa.DateTime(), nullable=True),
    sa.Column('toplam_tutar', sa.Float(), nullable=True),
    sa.Column('kdv_orani', sa.Float(), nullable=True),
    sa.Column('genel_toplam', sa.Float(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cari_id'], ['cari.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teklif_no')
    )
    op.create_table('avans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('tutar', sa.Float(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kesinti_turu', sa.String(length=50), nullable=True),
    sa.Column('taksit_sayisi', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('talep_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personel_id'], ['personel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('egitim_kaydi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('egitim_adi', sa.String(length=200), nullable=False),
    sa.Column('egitim_tipi', sa.String(length=50), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=True),
    sa.Column('bitis_tarihi', sa.Date(), nullable=True),
    sa.Column('sure', sa.Integer(), nullable=True),
    sa.Column('kurum', sa.String(length=200), nullable=True),
    sa.Column('sertifa_no', sa.String(length=100), nullable=True),
    sa.Column('ucret', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personel_id'], ['personel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iade_kalem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iade_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('urun_adi', sa.String(length=200), nullable=False),
    sa.Column('miktar', sa.Float(), nullable=False),
    sa.Column('birim_fiyat', sa.Float(), nullable=False),
    sa.Column('eski_stok', sa.Float(), nullable=True),
    sa.Column('yeni_stok', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['iade_id'], ['iade.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('izin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('izin_tipi', sa.String(length=50), nullable=False),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=False),
    sa.Column('bitis_tarihi', sa.Date(), nullable=False),
    sa.Column('gun_sayisi', sa.Integer(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('onay_durumu', sa.String(length=20), nullable=True),
    sa.Column('onaylayan', sa.Integer(), nullable=True),
    sa.Column('onay_tarihi', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('talep_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personel_id'], ['personel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maas_kaydi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('ay', sa.String(length=20), nullable=False),
    sa.Column('yil', sa.Integer(), nullable=False),
    sa.Column('brut_ucret', sa.Float(), nullable=False),
    sa.Column('net_ucret', sa.Float(), nullable=False),
    sa.Column('sgk_kesinti', sa.Float(), nullable=True),
    sa.Column('gelir_vergisi', sa.Float(), nullable=True),
    sa.Column('damga_vergisi', sa.Float(), nullable=True),
    sa.Column('diger_kesintiler', sa.Float(), nullable=True),
    sa.Column('odeme_durumu', sa.String(length=20), nullable=True),
    sa.Column('odeme_tarihi', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personel_id'], ['personel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personel_performans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('degerlendirme_tarihi', sa.Date(), nullable=False),
    sa.Column('degerlendiren', sa.Integer(), nullable=True),
    sa.Column('performans_puani', sa.Float(), nullable=True),
    sa.Column('hedeflere_uyum', sa.Float(), nullable=True),
    sa.Column('is_kalitesi', sa.Float(), nullable=True),
    sa.Column('takim_calismasi', sa.Float(), nullable=True),
    sa.Column('yenilikcilik', sa.Float(), nullable=True),
    sa.Column('aciklamalar', sa.Text(), nullable=True),
    sa.Column('gelişim_alanlari', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personel_id'], ['personel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('prim_tipi', sa.String(length=50), nullable=False),
    sa.Column('tutar', sa.Float(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('donem', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kayit_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personel_id'], ['personel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satis_kalemi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('satis_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('urun_adi', sa.String(length=200), nullable=False),
    sa.Column('barkod', sa.String(length=50), nullable=True),
    sa.Column('miktar', sa.Float(), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('birim_fiyat', sa.Float(), nullable=True),
    sa.Column('toplam', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['satis_id'], ['satis.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teklif_kalemi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teklif_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('urun_adi', sa.String(length=200), nullable=False),
    sa.Column('miktar', sa.Float(), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('birim_fiyat', sa.Float(), nullable=True),
    sa.Column('kdv_orani', sa.Float(), nullable=True),
    sa.Column('toplam', sa.Float(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['teklif_id'], ['teklif.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teklif_kalemi')
    op.drop_table('satis_kalemi')
    op.drop_table('prim')
    op.drop_table('personel_performans')
    op.drop_table('maas_kaydi')
    op.drop_table('izin')
    op.drop_table('iade_kalem')
    op.drop_table('egitim_kaydi')
    op.drop_table('avans')
    op.drop_table('teklif')
    op.drop_table('support_ticket_message')
    op.drop_table('stok_hareket')
    op.drop_table('satis')
    op.drop_table('personel')
    op.drop_table('iade')
    op.drop_table('cash_transaction')
    op.drop_table('cari_hareket')
    op.drop_table('action_item_event')
    op.drop_table('account_reconciliation')
    op.drop_table('warehouse')
    op.drop_table('urun')
    op.drop_table('system_settings')
    op.drop_table('support_ticket')
    op.drop_table('departman')
    op.drop_table('category')
    op.drop_table('cari')
    op.drop_table('backup_log')
    op.drop_table('audit_log')
    op.drop_table('action_item')
    op.drop_table('account')
    op.drop_table('user')
    op.drop_table('subscription_payment')
    op.drop_table('organization')
    # ### end Alembic commands ###
